package com.epalma.tvespanolplus;

import android.app.*;
import android.content.*;
import android.content.res.Configuration;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.StateListDrawable;
import android.net.*;
import android.os.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import androidx.media3.common.*;
import androidx.media3.common.util.UnstableApi;
import androidx.media3.exoplayer.ExoPlayer;
import androidx.media3.ui.PlayerView;
import androidx.media3.ui.AspectRatioFrameLayout;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

@UnstableApi
public class MainActivity extends Activity {
  static final int OPEN_M3U=7001;
  static final int NAVY=Color.rgb(2,9,20), PANEL=Color.rgb(7,24,43), CARD=Color.rgb(8,42,68), ACCENT=Color.rgb(0,198,255), CYAN=Color.rgb(0,212,255), BLUE=Color.rgb(0,110,253), MUTED=Color.rgb(167,179,199), GREEN=Color.rgb(40,199,111), PURPLE=Color.rgb(124,92,255), ORANGE=Color.rgb(255,193,7);
  static final int PV_SURFACE=Color.argb(246,5,24,43), PV_SURFACE_2=Color.argb(242,8,42,68), PV_BUTTON=Color.argb(242,8,42,68), PV_BUTTON_FOCUS=Color.argb(248,10,82,132), PV_PRIMARY=Color.rgb(0,110,253), PV_DANGER=Color.rgb(234,67,53), PV_ERROR=Color.rgb(234,67,53);
  final ExecutorService io=Executors.newSingleThreadExecutor();
  final List<Channel> all=new ArrayList<>(), shown=new ArrayList<>();
  final Map<String,List<Channel>> categoryIndex=new HashMap<>();
  final TreeMap<String,List<Channel>> countryIndex=new TreeMap<>();
  Runnable searchFilterTask;
  String activeSourceLabel="Lista principal";
  final LinkedHashSet<String> favorites=new LinkedHashSet<>();
  final ArrayDeque<String> recents=new ArrayDeque<>();
  ExoPlayer player; PlayerView playerView; FrameLayout homePlayerHolder, contentFrame;
  Channel current, previous; ArrayAdapter<String> adapter; ListView channelList; EditText search; TextView status,count,sourceText,title,screenTitle;
  Button favButton,homeButton,exitButton; View playerEmpty; String mode="all", category="Todos", page="home"; int retries=0, resizeMode=0, playToken=0; boolean autoRetryEnabled=true;
  final Handler mainHandler=new Handler(Looper.getMainLooper()); Runnable startupWatchdog; long connectStartedAt=0L; String lastHealth="Sin verificar";

  @Override public void onCreate(Bundle b){super.onCreate(b);loadPrefs();buildShell();initPlayer();showHome();loadSavedSource();}

  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  GradientDrawable rounded(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));d.setStroke(dp(1),Color.argb(165,26,157,255));return d;}
  StateListDrawable buttonBg(int normal,int pressed,int radius){StateListDrawable s=new StateListDrawable();s.addState(new int[]{android.R.attr.state_pressed},rounded(pressed,radius));s.addState(new int[]{android.R.attr.state_focused},rounded(pressed,radius));s.addState(new int[]{},rounded(normal,radius));return s;}
  TextView tv(String s,int sp,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
  Button btn(String s){return actionBtn(s,CARD);}
  Button actionBtn(String s,int ignored){return dsButton(s,0,false,false);}
  Button primaryBtn(String s){return dsButton(s,0,true,false);}
  Button dangerBtn(String s){return dsButton(s,0,false,true);}
  Button iconBtn(String s,int icon){return dsButton(s,icon,false,false);}
  Button primaryIconBtn(String s,int icon){return dsButton(s,icon,true,false);}
  Button dsButton(String s,int icon,boolean primary,boolean danger){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setMinHeight(dp(46));b.setSingleLine(true);b.setFocusable(true);b.setGravity(Gravity.CENTER);int n=danger?PV_DANGER:(primary?PV_PRIMARY:PV_BUTTON),f=danger?Color.rgb(196,48,38):(primary?Color.rgb(20,132,255):PV_BUTTON_FOCUS);b.setBackground(buttonBg(n,f,14));b.setPadding(dp(10),0,dp(10),0);if(icon!=0)setButtonIcon(b,icon,false);b.setOnFocusChangeListener((v,has)->{v.setScaleX(has?1.035f:1f);v.setScaleY(has?1.035f:1f);});return b;}
  Button controlBtn(String s,int icon){Button b=dsButton(s,0,false,false);b.setTextSize(9);b.setGravity(Gravity.CENTER);b.setSingleLine(true);b.setPadding(dp(2),dp(2),dp(2),dp(2));setButtonIcon(b,icon,true);return b;}
  void setButtonIcon(Button b,int res,boolean top){try{android.graphics.drawable.Drawable d=getDrawable(res).mutate();d.setTint(CYAN);d.setBounds(0,0,dp(top?20:18),dp(top?20:18));if(top)b.setCompoundDrawables(null,d,null,null);else b.setCompoundDrawables(d,null,null,null);b.setCompoundDrawablePadding(dp(top?4:7));}catch(Exception ignored){}}
  int blend(int a,int b,float f){int r=(int)(Color.red(a)*(1-f)+Color.red(b)*f),g=(int)(Color.green(a)*(1-f)+Color.green(b)*f),bl=(int)(Color.blue(a)*(1-f)+Color.blue(b)*f);return Color.rgb(r,g,bl);}
  LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(3),0,dp(3),0);return p;}

  void buildShell(){
    getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);
    boolean phone=getResources().getConfiguration().screenWidthDp<600;
    FrameLayout root=new FrameLayout(this);
    ImageView bg=new ImageView(this);bg.setImageResource(R.drawable.pv_background);bg.setScaleType(ImageView.ScaleType.CENTER_CROP);root.addView(bg,new FrameLayout.LayoutParams(-1,-1));
    View shade=new View(this);shade.setBackgroundColor(Color.argb(phone?220:205,0,7,19));root.addView(shade,new FrameLayout.LayoutParams(-1,-1));
    LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(phone?9:12),dp(5),dp(phone?9:12),dp(7));root.addView(shell,new FrameLayout.LayoutParams(-1,-1));
    shell.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(dp(phone?9:12)+in.getSystemWindowInsetLeft(),dp(5)+in.getSystemWindowInsetTop(),dp(phone?9:12)+in.getSystemWindowInsetRight(),dp(7)+in.getSystemWindowInsetBottom());return in;});
    LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(2),0,dp(2),0);
    ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.pv_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);top.addView(logo,new LinearLayout.LayoutParams(dp(phone?128:220),dp(phone?54:72)));
    screenTitle=tv("",1,Color.TRANSPARENT);screenTitle.setVisibility(View.GONE);top.addView(new Space(this),new LinearLayout.LayoutParams(0,dp(phone?48:64),1));
    sourceText=tv("",1,Color.TRANSPARENT);sourceText.setVisibility(View.GONE);
    homeButton=iconBtn(phone?"Inicio":"Menú principal",R.drawable.pv_ic_grid);exitButton=dangerBtn("Salir");exitButton.setVisibility(View.GONE);homeButton.setTextSize(phone?11:13);
    top.addView(homeButton,new LinearLayout.LayoutParams(dp(phone?72:150),dp(phone?42:46)));
    homeButton.setOnClickListener(v->showHome());exitButton.setOnClickListener(v->confirmExit());shell.addView(top,new LinearLayout.LayoutParams(-1,dp(phone?58:72)));
    contentFrame=new FrameLayout(this);shell.addView(contentFrame,new LinearLayout.LayoutParams(-1,0,1));
    setContentView(root);
  }

  void setPage(String key,String label){page=key;if(screenTitle!=null)screenTitle.setText("home".equals(key)?"":label);if(homeButton!=null)homeButton.setVisibility("home".equals(key)?View.GONE:View.VISIBLE);clearContent();}
  GradientDrawable outlinePanel(){GradientDrawable d=new GradientDrawable();d.setColor(PV_SURFACE);d.setCornerRadius(dp(18));d.setStroke(dp(1),Color.argb(190,0,198,255));return d;}
  GradientDrawable glassCard(){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(118,8,34,62),Color.argb(218,3,16,31)});d.setCornerRadius(dp(18));d.setStroke(dp(1),Color.argb(190,0,198,255));return d;}
  View categoryCard(String heading,String sub,int imageRes,Runnable action){boolean phone=getResources().getConfiguration().screenWidthDp<600;FrameLayout card=new FrameLayout(this);card.setBackground(glassCard());if(Build.VERSION.SDK_INT>=21)card.setClipToOutline(true);ImageView img=new ImageView(this);img.setImageResource(imageRes);img.setScaleType(ImageView.ScaleType.CENTER_CROP);card.addView(img,new FrameLayout.LayoutParams(-1,-1));View overlay=new View(this);GradientDrawable gd=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{Color.argb(205,2,10,23),Color.argb(72,2,10,23)});gd.setCornerRadius(dp(18));overlay.setBackground(gd);card.addView(overlay,new FrameLayout.LayoutParams(-1,-1));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.BOTTOM);box.setPadding(dp(phone?12:18),dp(10),dp(phone?48:62),dp(phone?11:14));TextView h=tv(heading,phone?16:23,Color.WHITE);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);TextView d=tv(sub,phone?10:14,MUTED);d.setMaxLines(2);box.addView(h,new LinearLayout.LayoutParams(-1,-2));box.addView(d,new LinearLayout.LayoutParams(-1,-2));card.addView(box,new FrameLayout.LayoutParams(-1,-1));ImageView arrow=new ImageView(this);arrow.setImageResource(R.drawable.pv_ic_chevron);arrow.setPadding(dp(phone?8:12),dp(phone?8:12),dp(phone?8:12),dp(phone?8:12));arrow.setBackground(buttonBg(Color.argb(225,4,40,82),Color.argb(245,17,88,156),18));FrameLayout.LayoutParams ap=new FrameLayout.LayoutParams(dp(phone?36:50),dp(phone?36:50),Gravity.BOTTOM|Gravity.RIGHT);ap.setMargins(0,0,dp(10),dp(10));card.addView(arrow,ap);card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->action.run());card.setOnFocusChangeListener((v,f)->{v.setScaleX(f?1.02f:1f);v.setScaleY(f?1.02f:1f);});return card;}

  void clearContent(){contentFrame.removeAllViews();}
  void showHome(){
    boolean phone=getResources().getConfiguration().screenWidthDp<600;
    setPage("home","Inicio");
    ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setVerticalScrollBarEnabled(false);contentFrame.addView(scroll,new FrameLayout.LayoutParams(-1,-1));
    LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(7),dp(7),dp(7),dp(12));panel.setBackground(outlinePanel());scroll.addView(panel,new ScrollView.LayoutParams(-1,-2));
    TextView prompt=tv("¿Qué deseas ver hoy?",phone?18:24,Color.WHITE);prompt.setTypeface(Typeface.DEFAULT,Typeface.BOLD);prompt.setPadding(dp(7),dp(4),dp(7),dp(4));panel.addView(prompt,new LinearLayout.LayoutParams(-1,dp(phone?38:46)));
    GridLayout grid=new GridLayout(this);grid.setColumnCount(2);grid.setRowCount(2);panel.addView(grid,new LinearLayout.LayoutParams(-1,phone?dp(330):dp(410)));
    View[] cards={
      categoryCard("Canales en vivo","TV en vivo · todas las categorías",R.drawable.home_live,this::showLiveCategories),
      categoryCard("Películas","Próximamente · bajo demanda",R.drawable.home_movies,()->showLibraryPlaceholder("Películas")),
      categoryCard("Series","Próximamente · bajo demanda",R.drawable.home_series,()->showLibraryPlaceholder("Series")),
      categoryCard("Música","Próximamente · biblioteca musical",R.drawable.home_music,()->showLibraryPlaceholder("Música"))};
    for(int i=0;i<cards.length;i++){GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=0;gp.rowSpec=GridLayout.spec(i/2,1f);gp.columnSpec=GridLayout.spec(i%2,1f);gp.setMargins(dp(4),dp(4),dp(4),dp(4));grid.addView(cards[i],gp);}
    TextView qa=tv("Accesos rápidos",12,MUTED);qa.setPadding(dp(5),dp(8),0,0);panel.addView(qa,new LinearLayout.LayoutParams(-1,dp(32)));
    GridLayout quick=new GridLayout(this);quick.setColumnCount(2);quick.setRowCount(2);quick.setPadding(0,dp(3),0,0);panel.addView(quick,new LinearLayout.LayoutParams(-1,phone?dp(108):dp(120)));
    String[] labs={"Buscar","Favoritos","Recientes","Configuración"};int[] icons={R.drawable.pv_ic_search,R.drawable.pv_ic_star,R.drawable.pv_ic_history,R.drawable.pv_ic_settings};Runnable[] acts={()->{showLivePlayer("Todos");if(search!=null){search.requestFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,InputMethodManager.SHOW_IMPLICIT);}},()->showSavedPage("Favoritos",true),()->showSavedPage("Recientes",false),this::showSettings};
    for(int i=0;i<labs.length;i++){Button b=iconBtn(labs[i],icons[i]);b.setTextSize(phone?12:14);final int k=i;b.setOnClickListener(v->acts[k].run());GridLayout.LayoutParams qp=new GridLayout.LayoutParams();qp.width=0;qp.height=0;qp.rowSpec=GridLayout.spec(i/2,1f);qp.columnSpec=GridLayout.spec(i%2,1f);qp.setMargins(dp(4),dp(4),dp(4),dp(4));quick.addView(b,qp);}
  }

  int countCategory(String cat){List<Channel> b=baseForCategory(cat);return b==null?0:b.size();}
  void addIndex(Map<String,List<Channel>> map,String key,Channel ch){List<Channel> x=map.get(key);if(x==null){x=new ArrayList<>();map.put(key,x);}x.add(ch);}
  String canonicalCategory(Channel ch){String raw=ch.group==null?"":ch.group.trim(),clean=cleanGroup(raw).toLowerCase(Locale.ROOT);if(raw.startsWith("01 ")||clean.contains("deport")||clean.contains("sport"))return "Deportes";if(raw.startsWith("02 ")||clean.contains("cine"))return "Cine en vivo";if(raw.startsWith("03 ")||clean.contains("serie"))return "Series en vivo";if(raw.startsWith("04 ")||clean.contains("crist")||clean.contains("relig"))return "Religiosos";if(raw.startsWith("05 ")||clean.contains("noticia")||clean.contains("news"))return "Noticias";if(raw.startsWith("06 ")||clean.contains("infantil")||clean.contains("kids"))return "Infantiles";if(raw.startsWith("07 ")||clean.contains("música")||clean.contains("musica")||clean.contains("music"))return "Música";if(raw.startsWith("08 ")||clean.contains("document")||clean.contains("cultura"))return "Documentales";if(raw.startsWith("09 ")||clean.contains("entreten"))return "Entretenimiento";return "Otros";}
  void rebuildChannelIndex(){categoryIndex.clear();countryIndex.clear();for(Channel ch:all){addIndex(categoryIndex,canonicalCategory(ch),ch);String raw=ch.group==null?"":ch.group.trim();if(raw.startsWith("20 "))addIndex(countryIndex,cleanGroup(raw),ch);}}
  List<Channel> baseForCategory(String cat){if(cat==null||"Todos".equals(cat))return all;if(cat.startsWith("País:")){List<Channel> x=countryIndex.get(cat.substring(5));return x==null?Collections.emptyList():x;}List<Channel> x=categoryIndex.get(cat);return x==null?Collections.emptyList():x;}
  View liveCategoryCard(String title,String cat,int icon){boolean phone=getResources().getConfiguration().screenWidthDp<600;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setPadding(dp(8),dp(8),dp(8),dp(6));card.setBackground(glassCard());ImageView iv=new ImageView(this);iv.setImageResource(icon);iv.setScaleType(ImageView.ScaleType.CENTER_INSIDE);card.addView(iv,new LinearLayout.LayoutParams(dp(phone?30:40),dp(phone?30:40)));TextView h=tv(title,phone?13:17,Color.WHITE);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setGravity(Gravity.CENTER);card.addView(h,new LinearLayout.LayoutParams(-1,dp(phone?28:32)));TextView ct=tv(countCategory(cat)+" canales",phone?10:12,MUTED);ct.setGravity(Gravity.CENTER);card.addView(ct,new LinearLayout.LayoutParams(-1,dp(20)));card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->{v.setEnabled(false);mainHandler.post(()->showLivePlayer(cat));});card.setOnFocusChangeListener((v,f)->{v.setScaleX(f?1.025f:1f);v.setScaleY(f?1.025f:1f);});return card;}
  void showLiveCategories(){boolean phone=getResources().getConfiguration().screenWidthDp<600;setPage("livecats","Canales en vivo");ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);contentFrame.addView(scroll,new FrameLayout.LayoutParams(-1,-1));LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(8),dp(8),dp(8),dp(10));panel.setBackground(outlinePanel());scroll.addView(panel,new ScrollView.LayoutParams(-1,-2));TextView h=tv("Canales en vivo",phone?20:26,Color.WHITE);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(dp(7),dp(3),0,0);panel.addView(h,new LinearLayout.LayoutParams(-1,dp(38)));TextView sub=tv("Elige una categoría de la lista M3U",12,MUTED);sub.setPadding(dp(7),0,0,dp(6));panel.addView(sub,new LinearLayout.LayoutParams(-1,dp(34)));GridLayout grid=new GridLayout(this);grid.setColumnCount(phone?2:3);panel.addView(grid,new LinearLayout.LayoutParams(-1,phone?dp(780):dp(620)));String[] titles={"Todos","Deportes","Noticias","Cine en vivo","Series en vivo","Música","Religiosos","Infantiles","Documentales","Entretenimiento"};String[] cats={"Todos","Deportes","Noticias","Cine en vivo","Series en vivo","Música","Religiosos","Infantiles","Documentales","Entretenimiento"};int[] icons={R.drawable.pv_ic_grid,R.drawable.pv_ic_sports,R.drawable.pv_ic_news,R.drawable.pv_ic_movies,R.drawable.pv_ic_series,R.drawable.pv_ic_music,R.drawable.pv_ic_heart,R.drawable.pv_ic_kids,R.drawable.pv_ic_globe,R.drawable.pv_ic_star};for(int i=0;i<titles.length;i++){View card=liveCategoryCard(titles[i],cats[i],icons[i]);GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=0;gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.rowSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(dp(5),dp(5),dp(5),dp(5));grid.addView(card,gp);}Button countries=primaryIconBtn("Explorar por país",R.drawable.pv_ic_globe);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(54));cp.setMargins(dp(5),dp(8),dp(5),dp(3));panel.addView(countries,cp);countries.setOnClickListener(v->showCountries());}
  void showCountries(){setPage("countries","Explorar por país");ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);contentFrame.addView(scroll,new FrameLayout.LayoutParams(-1,-1));LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(10),dp(8),dp(10),dp(10));panel.setBackground(outlinePanel());scroll.addView(panel,new ScrollView.LayoutParams(-1,-2));TextView h=tv("Canales por país",20,Color.WHITE);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);panel.addView(h,new LinearLayout.LayoutParams(-1,dp(38)));GridLayout grid=new GridLayout(this);grid.setColumnCount(2);panel.addView(grid,new LinearLayout.LayoutParams(-1,-2));for(Map.Entry<String,List<Channel>> e:countryIndex.entrySet()){Button b=iconBtn(e.getKey()+" · "+e.getValue().size(),R.drawable.pv_ic_globe);b.setTextSize(11);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);final String cat="País:"+e.getKey();b.setOnClickListener(v->{v.setEnabled(false);mainHandler.post(()->showLivePlayer(cat));});GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(52);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(dp(4),dp(4),dp(4),dp(4));grid.addView(b,gp);}}
  void showLibraryPlaceholder(String section){LinearLayout p=pageBase(section,"Próximamente");TextView t=tv(section+" bajo demanda estará disponible cuando se conecte su biblioteca o servidor dedicado.\n\nLos canales en vivo de esta temática están dentro de Canales en vivo.",15,Color.WHITE);t.setGravity(Gravity.CENTER);t.setPadding(dp(20),dp(24),dp(20),dp(24));p.addView(t,new LinearLayout.LayoutParams(-1,0,1));Button back=primaryIconBtn("Volver al inicio",R.drawable.pv_ic_back);p.addView(back,new LinearLayout.LayoutParams(-1,dp(52)));back.setOnClickListener(v->showHome());}

  void showLive(){showLivePlayer("Todos");}

  void showLivePlayer(String selectedCategory){
    setPage("live","Canales en vivo");mode="all";category=selectedCategory==null?"Todos":selectedCategory;
    LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(10),dp(4),dp(10),dp(8));contentFrame.addView(page,new FrameLayout.LayoutParams(-1,-1));
    LinearLayout searchRow=new LinearLayout(this);searchRow.setGravity(Gravity.CENTER_VERTICAL);
    search=new EditText(this);search.setSingleLine(true);search.setHint("Buscar canal, país o categoría…");search.setTextColor(Color.WHITE);search.setHintTextColor(MUTED);search.setTextSize(14);search.setBackground(rounded(PV_SURFACE_2,14));search.setPadding(dp(14),0,dp(8),0);android.graphics.drawable.Drawable clearIcon=getDrawable(R.drawable.pv_ic_close).mutate();clearIcon.setTint(CYAN);clearIcon.setBounds(0,0,dp(20),dp(20));search.setCompoundDrawables(null,null,clearIcon,null);search.setCompoundDrawablePadding(dp(8));searchRow.addView(search,new LinearLayout.LayoutParams(0,dp(48),1));
    Button doSearch=primaryIconBtn("Buscar",R.drawable.pv_ic_search);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(100),dp(48));sp.setMargins(dp(7),0,0,0);searchRow.addView(doSearch,sp);page.addView(searchRow,new LinearLayout.LayoutParams(-1,dp(48)));
    doSearch.setOnClickListener(v->{filter();search.clearFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(search.getWindowToken(),0);});search.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_UP&&search.getCompoundDrawables()[2]!=null&&e.getX()>=search.getWidth()-search.getPaddingRight()-dp(32)){search.setText("");filter();return true;}return false;});
    LinearLayout categoryBar=new LinearLayout(this);categoryBar.setGravity(Gravity.CENTER_VERTICAL);categoryBar.setPadding(0,dp(5),0,dp(6));
    Button backCats=iconBtn("Categorías",R.drawable.pv_ic_back);categoryBar.addView(backCats,new LinearLayout.LayoutParams(dp(112),dp(42)));
    TextView activeCat=tv("Canales en vivo  ·  "+displayCategory(category),14,Color.WHITE);activeCat.setTypeface(Typeface.DEFAULT,Typeface.BOLD);activeCat.setGravity(Gravity.CENTER_VERTICAL);activeCat.setPadding(dp(10),0,0,0);categoryBar.addView(activeCat,new LinearLayout.LayoutParams(0,dp(42),1));
    backCats.setOnClickListener(v->showLiveCategories());page.addView(categoryBar,new LinearLayout.LayoutParams(-1,dp(53)));

    LinearLayout body=new LinearLayout(this);boolean wide=getResources().getConfiguration().screenWidthDp>=700;body.setOrientation(wide?LinearLayout.HORIZONTAL:LinearLayout.VERTICAL);page.addView(body,new LinearLayout.LayoutParams(-1,0,1));
    LinearLayout playerCard=buildPlayerCard();LinearLayout listCard=buildChannelList();
    if(wide){body.addView(listCard,new LinearLayout.LayoutParams(dp(335),-1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,-1,1);rp.setMargins(dp(10),0,0,0);body.addView(playerCard,rp);}else{body.addView(playerCard,new LinearLayout.LayoutParams(-1,dp(355)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,0,1);lp.setMargins(0,dp(8),0,0);body.addView(listCard,lp);}
    bindList();filter();
  }

  LinearLayout buildPlayerCard(){
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackground(glassCard());card.setPadding(dp(6),dp(6),dp(6),dp(6));
    title=tv(current==null?"Selecciona un canal para comenzar":current.name,18,Color.WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setPadding(dp(8),0,dp(8),0);card.addView(title,new LinearLayout.LayoutParams(-1,dp(42)));
    homePlayerHolder=new FrameLayout(this);homePlayerHolder.setBackgroundColor(Color.BLACK);card.addView(homePlayerHolder,new LinearLayout.LayoutParams(-1,0,1));
    attachMainPlayer();
    if(current==null){LinearLayout empty=new LinearLayout(this);empty.setOrientation(LinearLayout.VERTICAL);empty.setGravity(Gravity.CENTER);ImageView mark=new ImageView(this);mark.setImageResource(com.epalma.tvespanolplus.R.drawable.pv_logo);mark.setAlpha(.82f);empty.addView(mark,new LinearLayout.LayoutParams(dp(84),dp(84)));TextView msg=tv("PalmaVision\nElige un canal en vivo",14,Color.WHITE);msg.setGravity(Gravity.CENTER);msg.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);empty.addView(msg,new LinearLayout.LayoutParams(-1,dp(54)));playerEmpty=empty;homePlayerHolder.addView(empty,new FrameLayout.LayoutParams(-1,-1));}
    status=tv(current==null?"Listo para reproducir":"En vivo",12,current==null?MUTED:CYAN);status.setPadding(dp(8),0,dp(8),0);card.addView(status,new LinearLayout.LayoutParams(-1,dp(30)));
    LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);Button prev=controlBtn("Anterior",R.drawable.pv_ic_prev),next=controlBtn("Siguiente",R.drawable.pv_ic_next),retry=controlBtn("Reintentar",R.drawable.pv_ic_refresh),more=controlBtn("Más",R.drawable.pv_ic_more);favButton=controlBtn("Favorito",R.drawable.pv_ic_star);
    for(Button b:new Button[]{prev,favButton,next,retry,more}){b.setGravity(Gravity.CENTER);controls.addView(b,weight());}card.addView(controls,new LinearLayout.LayoutParams(-1,dp(58)));
    LinearLayout videoTools=new LinearLayout(this);videoTools.setGravity(Gravity.CENTER);Button full=primaryIconBtn("Pantalla completa",R.drawable.pv_ic_fullscreen),fit=iconBtn(resizeModeName(),R.drawable.pv_ic_crop);videoTools.addView(full,weight());videoTools.addView(fit,weight());card.addView(videoTools,new LinearLayout.LayoutParams(-1,dp(50)));
    prev.setOnClickListener(v->step(-1));next.setOnClickListener(v->step(1));retry.setOnClickListener(v->{retries=0;restart();});favButton.setOnClickListener(v->toggleFavorite());more.setOnClickListener(v->showMoreMenu());full.setOnClickListener(v->openFullscreen());fit.setOnClickListener(v->{cycleResizeMode();fit.setText(resizeModeName());});updateFav();return card;
  }

  LinearLayout buildChannelList(){
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackground(glassCard());
    count=tv("Cargando…",12,MUTED);count.setPadding(dp(12),0,dp(8),0);card.addView(count,new LinearLayout.LayoutParams(-1,dp(34)));
    channelList=new ListView(this);channelList.setDivider(new ColorDrawable(Color.rgb(27,48,67)));channelList.setDividerHeight(1);card.addView(channelList,new LinearLayout.LayoutParams(-1,0,1));return card;
  }

  void attachMainPlayer(){if(playerView==null){playerView=new PlayerView(this);playerView.setUseController(true);playerView.setShowBuffering(PlayerView.SHOW_BUFFERING_WHEN_PLAYING);playerView.setFocusable(true);}applyResizeMode(playerView);ViewParent p=playerView.getParent();if(p instanceof ViewGroup)((ViewGroup)p).removeView(playerView);if(homePlayerHolder!=null){homePlayerHolder.addView(playerView,0,new FrameLayout.LayoutParams(-1,-1));if(player!=null)playerView.setPlayer(player);}}

  void initPlayer(){player=new ExoPlayer.Builder(this).build();player.addListener(new Player.Listener(){
    @Override public void onPlaybackStateChanged(int s){
      if(s==Player.STATE_READY){cancelStartupWatchdog();retries=0;setLiveStatus("En vivo"+channelPositionText(),CYAN);}
      else if(s==Player.STATE_BUFFERING)setLiveStatus(retries>0?"Reconectando "+retries+"/3…":"Cargando señal…",CYAN);
      else if(s==Player.STATE_ENDED)setLiveStatus("Transmisión finalizada",ORANGE);
    }
    @Override public void onIsPlayingChanged(boolean playing){if(playing&&player.getPlaybackState()==Player.STATE_READY)setLiveStatus("En vivo"+channelPositionText(),CYAN);}
    @Override public void onPlayerError(PlaybackException e){cancelStartupWatchdog();setLiveStatus(errorLabel(e),ORANGE);if(autoRetryEnabled)autoRetry();}
  });attachMainPlayer();}

  void bindList(){adapter=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,new ArrayList<String>()){@Override public View getView(int p,View c,ViewGroup parent){TextView v=(TextView)super.getView(p,c,parent);v.setTextColor(Color.WHITE);v.setTextSize(13);v.setPadding(dp(12),dp(5),dp(8),dp(5));v.setMinHeight(dp(50));boolean active=p<shown.size()&&current!=null&&shown.get(p).id.equals(current.id);v.setBackground(rounded(active?PV_PRIMARY:Color.argb(225,6,29,50),12));return v;}};channelList.setAdapter(adapter);channelList.setOnItemClickListener((p,v,pos,id)->play(shown.get(pos)));channelList.setOnItemLongClickListener((p,v,pos,id)->{Channel ch=shown.get(pos);toggleFavorite(ch);filter();toast(favorites.contains(ch.id)?"Añadido a favoritos":"Eliminado de favoritos");return true;});search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){if(searchFilterTask!=null)mainHandler.removeCallbacks(searchFilterTask);searchFilterTask=MainActivity.this::filter;mainHandler.postDelayed(searchFilterTask,180);}public void afterTextChanged(android.text.Editable e){}});}

  String cleanGroup(String raw){if(raw==null)return "Otros";String s=raw.trim().replaceFirst("^\\d+\\s+","").replaceFirst("^[^\\p{L}\\p{N}]+","").trim();return s.isEmpty()?"Otros":s;}
  String displayCategory(String cat){return cat!=null&&cat.startsWith("País:")?cat.substring(5):cat;}
  boolean categoryMatch(Channel c,String cat){if(cat==null||cat.equals("Todos"))return true;String raw=c.group==null?"":c.group.trim();String clean=cleanGroup(raw);if(cat.startsWith("País:"))return raw.startsWith("20 ")&&clean.equalsIgnoreCase(cat.substring(5));if(cat.equals("Deportes"))return raw.startsWith("01 ")||clean.equalsIgnoreCase("Deportes");if(cat.equals("Cine en vivo"))return raw.startsWith("02 ")||clean.equalsIgnoreCase("Cine en vivo");if(cat.equals("Series en vivo"))return raw.startsWith("03 ")||clean.equalsIgnoreCase("Series en vivo");if(cat.equals("Religiosos"))return raw.startsWith("04 ")||clean.toLowerCase(Locale.ROOT).contains("cristian");if(cat.equals("Noticias"))return raw.startsWith("05 ")||clean.equalsIgnoreCase("Noticias");if(cat.equals("Infantiles"))return raw.startsWith("06 ")||clean.toLowerCase(Locale.ROOT).contains("infantil");if(cat.equals("Música"))return raw.startsWith("07 ")||clean.equalsIgnoreCase("Música");if(cat.equals("Documentales"))return raw.startsWith("08 ")||clean.toLowerCase(Locale.ROOT).contains("document");if(cat.equals("Entretenimiento"))return raw.startsWith("09 ")||clean.equalsIgnoreCase("Entretenimiento");return clean.equalsIgnoreCase(cat);}
  boolean has(String x,String...keys){for(String k:keys)if(x.contains(k))return true;return false;}

  void filter(){if(adapter==null||search==null)return;String q=search.getText().toString().trim().toLowerCase(Locale.ROOT);shown.clear();Set<String> recentSet=new HashSet<>(recents);List<Channel> base=baseForCategory(category);for(Channel c:base){boolean mm=mode.equals("all")||(mode.equals("fav")&&favorites.contains(c.id))||(mode.equals("recent")&&recentSet.contains(c.id));if(mm&&(q.isEmpty()||c.search.contains(q)))shown.add(c);}if(mode.equals("recent")){final Map<String,Integer> rank=new HashMap<>();int i=0;for(String id:recents)rank.put(id,i++);Collections.sort(shown,(a,b)->Integer.compare(rank.containsKey(a.id)?rank.get(a.id):9999,rank.containsKey(b.id)?rank.get(b.id):9999));}List<String> names=new ArrayList<>(shown.size());for(Channel c:shown)names.add(c.name+"\n"+cleanGroup(c.group));adapter.clear();adapter.addAll(names);adapter.notifyDataSetChanged();count.setText(category.equals("Todos")?shown.size()+" canales":shown.size()+" canales · "+displayCategory(category));}

  void play(Channel c){if(c==null)return;if(!networkConnected()){setLiveStatus("Sin conexión de red",ORANGE);return;}if(current!=null&&!current.id.equals(c.id))previous=current;current=c;retries=0;addRecent(c.id);if(title!=null)title.setText(c.name+"  ·  "+cleanGroup(c.group));setLiveStatus("Conectando…",CYAN);if(playerEmpty!=null)playerEmpty.setVisibility(View.GONE);updateFav();startCurrentStream();filter();}
  void startCurrentStream(){if(current==null)return;playToken++;connectStartedAt=SystemClock.elapsedRealtime();player.setMediaItem(new MediaItem.Builder().setUri(current.url).setMediaId(current.id).build());player.prepare();player.play();armStartupWatchdog(playToken);}
  void restart(){if(current==null)return;if(!networkConnected()){setLiveStatus("Sin conexión de red · toca Reconectar",ORANGE);return;}setLiveStatus(retries>0?"Reconectando "+retries+"/3…":"Reconectando…",CYAN);startCurrentStream();}
  void autoRetry(){if(current==null)return;if(retries<3){retries++;setLiveStatus("Reconectando "+retries+"/3…",CYAN);mainHandler.postDelayed(this::restart,700L+retries*700L);}else setLiveStatus("Canal sin respuesta · prueba Verificar",ORANGE);}
  void step(int d){List<Channel> base=!shown.isEmpty()&&current!=null&&shown.contains(current)?shown:all;if(base.isEmpty())return;int i=current==null?-1:base.indexOf(current);if(i<0)i=0;else i=(i+d+base.size())%base.size();play(base.get(i));}
  void toggleFavorite(){toggleFavorite(current);}
  void toggleFavorite(Channel c){if(c==null)return;if(!favorites.add(c.id))favorites.remove(c.id);savePrefs();updateFav();}
  void updateFav(){if(favButton!=null){boolean on=current!=null&&favorites.contains(current.id);favButton.setText(on?"Guardado":"Favorito");favButton.setBackground(buttonBg(on?PV_PRIMARY:PV_BUTTON,on?Color.rgb(20,132,255):PV_BUTTON_FOCUS,14));setButtonIcon(favButton,R.drawable.pv_ic_star,true);}}
  void addRecent(String id){recents.remove(id);recents.addFirst(id);while(recents.size()>30)recents.removeLast();savePrefs();}

  void showMoreMenu(){LinearLayout p=pageBase("Opciones del reproductor","Controles del canal actual");Button full=menuCard("Pantalla completa","Aprovecha toda la pantalla",R.drawable.pv_ic_fullscreen),fit=menuCard("Ajuste de imagen · "+resizeModeName(),"Ajustar, llenar, estirar u original",R.drawable.pv_ic_crop),check=menuCard("Verificar canal","Comprueba si el enlace actual responde",R.drawable.pv_ic_info),audio=menuCard("Audio","Selecciona la pista de audio",R.drawable.pv_ic_audio),subs=menuCard("Subtítulos","Activa o cambia subtítulos",R.drawable.pv_ic_subtitles);for(Button b:new Button[]{full,fit,check,audio,subs}){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(62));lp.setMargins(dp(4),dp(4),dp(4),dp(4));p.addView(b,lp);}full.setOnClickListener(v->openFullscreen());fit.setOnClickListener(v->{cycleResizeMode();showMoreMenu();});check.setOnClickListener(v->validateCurrent());audio.setOnClickListener(v->showTracks(C.TRACK_TYPE_AUDIO));subs.setOnClickListener(v->showTracks(C.TRACK_TYPE_TEXT));}

  void showTracks(int type){if(current==null){toast("Seleccione un canal primero");return;}Tracks t=player.getCurrentTracks();final List<TrackSelectionOverride> ovs=new ArrayList<>();final List<String> labels=new ArrayList<>();if(type==C.TRACK_TYPE_TEXT)labels.add("Desactivados");for(Tracks.Group g:t.getGroups()){if(g.getType()!=type)continue;for(int i=0;i<g.length;i++){Format f=g.getTrackFormat(i);String l=f.label!=null?f.label:(f.language!=null?f.language:(type==C.TRACK_TYPE_AUDIO?"Audio ":"Subtítulo ")+(labels.size()+1));labels.add(l);ovs.add(new TrackSelectionOverride(g.getMediaTrackGroup(),i));}}if(labels.isEmpty()||(type==C.TRACK_TYPE_TEXT&&labels.size()==1)){toast(type==C.TRACK_TYPE_AUDIO?"No hay pistas de audio adicionales":"Este canal no ofrece subtítulos");return;}AlertDialog td=new AlertDialog.Builder(this).setTitle(type==C.TRACK_TYPE_AUDIO?"Audio":"Subtítulos").setItems(labels.toArray(new String[0]),(d,w)->{TrackSelectionParameters.Builder b=player.getTrackSelectionParameters().buildUpon();if(type==C.TRACK_TYPE_TEXT&&w==0)b.setTrackTypeDisabled(C.TRACK_TYPE_TEXT,true);else{int x=type==C.TRACK_TYPE_TEXT?w-1:w;b.setTrackTypeDisabled(type,false);b.setOverrideForType(ovs.get(x));}player.setTrackSelectionParameters(b.build());}).create();styleDialog(td);}

  void showSavedPage(String label,boolean fav){clearContent();LinearLayout page=pageBase(label,fav?"Tus canales guardados":"Últimos canales vistos");List<Channel> data=new ArrayList<>();if(fav){for(Channel c:all)if(favorites.contains(c.id))data.add(c);}else{for(String id:recents)for(Channel c:all)if(c.id.equals(id)){data.add(c);break;}}addChannelRows(page,data);}
  void showCategories(){showLiveCategories();}
  void showCategoryChannels(String cat){showLivePlayer(cat);}
  LinearLayout pageBase(String head,String sub){setPage(head.toLowerCase(Locale.ROOT),head);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(10),dp(8),dp(10),dp(10));p.setBackground(outlinePanel());contentFrame.addView(p,new FrameLayout.LayoutParams(-1,-1));TextView h=tv(head,getResources().getConfiguration().screenWidthDp<600?20:24,Color.WHITE);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(dp(8),dp(2),dp(8),0);p.addView(h,new LinearLayout.LayoutParams(-1,dp(34)));TextView s=tv(sub,12,CYAN);s.setPadding(dp(8),0,dp(8),dp(7));p.addView(s,new LinearLayout.LayoutParams(-1,dp(28)));return p;}
  Button menuCard(String title,String sub,int icon){Button b=iconBtn(title+"\n"+sub,icon);b.setSingleLine(false);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setTextSize(13);b.setPadding(dp(16),0,dp(12),0);return b;}
  void addChannelRows(LinearLayout page,List<Channel> data){ListView lv=new ListView(this);ArrayList<String> labels=new ArrayList<>();for(Channel c:data)labels.add(c.name+"\n"+cleanGroup(c.group));ArrayAdapter<String>a=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,labels){@Override public View getView(int p,View c,ViewGroup parent){TextView v=(TextView)super.getView(p,c,parent);v.setTextColor(Color.WHITE);v.setTextSize(13);v.setPadding(dp(14),dp(6),dp(10),dp(6));v.setBackground(rounded(Color.argb(225,6,29,50),12));return v;}};lv.setAdapter(a);lv.setDivider(new ColorDrawable(Color.rgb(27,48,67)));lv.setDividerHeight(1);page.addView(lv,new LinearLayout.LayoutParams(-1,0,1));lv.setOnItemClickListener((p,v,pos,id)->{Channel c=data.get(pos);showLivePlayer("Todos");play(c);});if(data.isEmpty()){TextView empty=tv("No hay canales en esta sección.",14,MUTED);page.addView(empty,new LinearLayout.LayoutParams(-1,dp(50)));}}

  void showSettings(){clearContent();LinearLayout page=pageBase("Configuración","PalmaVision v2.0.3 Performance & Sources");
    Switch retry=new Switch(this);retry.setText("Reconexión automática");retry.setTextColor(Color.WHITE);retry.setChecked(autoRetryEnabled);retry.setBackground(rounded(PV_BUTTON,14));retry.setPadding(dp(12),0,dp(12),0);page.addView(retry,new LinearLayout.LayoutParams(-1,dp(60)));
    Button lists=menuCard("Listas M3U","Administra tus fuentes",R.drawable.pv_ic_list), audio=menuCard("Audio","Pistas disponibles del canal",R.drawable.pv_ic_audio), subs=menuCard("Subtítulos","Activa o cambia subtítulos",R.drawable.pv_ic_subtitles),screen=menuCard("Pantalla y formato","Pantalla completa · "+resizeModeName(),R.drawable.pv_ic_crop),diag=menuCard("Diagnóstico y seguridad","Estado de red y permisos",R.drawable.pv_ic_info),about=menuCard("Acerca de PalmaVision","Versión y plataforma",R.drawable.pv_ic_info);
    for(Button b:new Button[]{lists,audio,subs,screen,diag,about}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,dp(5),0,0);page.addView(b,p);}Button exit= dangerBtn("Salir de PalmaVision");LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(52));ep.setMargins(0,dp(10),0,0);page.addView(exit,ep);exit.setOnClickListener(v->confirmExit());retry.setOnCheckedChangeListener((v,on)->{autoRetryEnabled=on;savePrefs();});lists.setOnClickListener(v->showLists());audio.setOnClickListener(v->showTracks(C.TRACK_TYPE_AUDIO));subs.setOnClickListener(v->showTracks(C.TRACK_TYPE_TEXT));screen.setOnClickListener(v->showMoreMenu());diag.setOnClickListener(v->diagnostics());about.setOnClickListener(v->pvMessage("PalmaVision","Versión 2.0.3 Performance & Sources\nMedia3 / ExoPlayer\nAndroid / Android TV\n\nDesign System unificado · motor LIVE estable"));}

  EditText sourceField(String hint,boolean password){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextColor(Color.WHITE);e.setHintTextColor(MUTED);e.setTextSize(14);e.setPadding(dp(12),0,dp(12),0);e.setBackground(rounded(PV_SURFACE_2,12));if(password)e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}
  SharedPreferences.Editor clearSourceKeys(SharedPreferences.Editor e){return e.remove("m3u_uri").remove("m3u_url").remove("xtream_server").remove("xtream_user").remove("xtream_pass").remove("source_type");}
  void showLists(){clearContent();LinearLayout page=pageBase("Fuentes de TV","Elige cómo cargar tus canales");TextView current=tv("Fuente actual  ·  "+activeSourceLabel,13,CYAN);current.setPadding(dp(12),dp(8),dp(12),dp(8));current.setBackground(rounded(PV_SURFACE_2,12));page.addView(current,new LinearLayout.LayoutParams(-1,dp(48)));Button principal=menuCard("Lista PalmaVision","Lista principal incluida · 1,733 canales",R.drawable.pv_ic_list),local=menuCard("Archivo M3U local","Selecciona un archivo desde el teléfono",R.drawable.pv_ic_list),url=menuCard("URL M3U","Carga una lista mediante enlace directo",R.drawable.pv_ic_globe),xtream=menuCard("Servidor IPTV / Xtream","URL + usuario + contraseña",R.drawable.pv_ic_settings);for(Button b:new Button[]{principal,local,url,xtream}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(68));p.setMargins(0,dp(7),0,0);page.addView(b,p);}principal.setOnClickListener(v->{SharedPreferences.Editor e=getSharedPreferences("tvplus",MODE_PRIVATE).edit();clearSourceKeys(e).putString("source_type","default").apply();loadDefault();showLiveCategories();});local.setOnClickListener(v->pickM3u());url.setOnClickListener(v->askUrl());xtream.setOnClickListener(v->askXtream());}
  void pickM3u(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,OPEN_M3U);}
  @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==OPEN_M3U&&res==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}SharedPreferences.Editor e=getSharedPreferences("tvplus",MODE_PRIVATE).edit();clearSourceKeys(e).putString("source_type","local").putString("m3u_uri",u.toString()).apply();loadFromUri(u,"Archivo M3U local");showLiveCategories();}}
  void askUrl(){final EditText e=sourceField("https://servidor/lista.m3u",false);AlertDialog d=new AlertDialog.Builder(this).setTitle("URL M3U").setView(e).setNegativeButton("Cancelar",null).setPositiveButton("Cargar",(x,w)->{String u=e.getText().toString().trim();if(u.startsWith("http://")||u.startsWith("https://")){SharedPreferences.Editor ed=getSharedPreferences("tvplus",MODE_PRIVATE).edit();clearSourceKeys(ed).putString("source_type","url").putString("m3u_url",u).apply();loadFromUrl(u,"URL M3U");showLiveCategories();}else toast("Ingrese una URL válida");}).create();styleDialog(d);}
  void askXtream(){SharedPreferences p=getSharedPreferences("tvplus",MODE_PRIVATE);LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(16),dp(8),dp(16),0);EditText server=sourceField("URL del servidor · http(s)://host:puerto",false),user=sourceField("Usuario",false),pass=sourceField("Contraseña",true);server.setText(p.getString("xtream_server",""));user.setText(p.getString("xtream_user",""));pass.setText(p.getString("xtream_pass",""));for(EditText f:new EditText[]{server,user,pass}){LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(50));fp.setMargins(0,dp(6),0,0);form.addView(f,fp);}AlertDialog d=new AlertDialog.Builder(this).setTitle("Servidor IPTV / Xtream").setView(form).setNegativeButton("Cancelar",null).setPositiveButton("Conectar",(x,w)->{String s=server.getText().toString().trim(),u=user.getText().toString().trim(),pw=pass.getText().toString();if(!(s.startsWith("http://")||s.startsWith("https://"))||u.isEmpty()||pw.isEmpty()){toast("Completa URL, usuario y contraseña");return;}SharedPreferences.Editor ed=getSharedPreferences("tvplus",MODE_PRIVATE).edit();clearSourceKeys(ed).putString("source_type","xtream").putString("xtream_server",s).putString("xtream_user",u).putString("xtream_pass",pw).apply();loadXtream(s,u,pw);showLiveCategories();}).create();styleDialog(d);}
  String xtreamM3uUrl(String server,String user,String pass){try{String s=server.endsWith("/")?server.substring(0,server.length()-1):server;return s+"/get.php?username="+URLEncoder.encode(user,"UTF-8")+"&password="+URLEncoder.encode(pass,"UTF-8")+"&type=m3u_plus&output=ts";}catch(Exception e){return "";}}
  void loadXtream(String server,String user,String pass){String u=xtreamM3uUrl(server,user,pass);if(u.isEmpty()){toast("No se pudo construir la URL del servidor");return;}loadFromUrl(u,"Servidor IPTV · "+user);}

  String resizeModeName(){switch(resizeMode){case 1:return "Llenar";case 2:return "Estirar";case 3:return "Original";default:return "Ajustar";}}
  void applyResizeMode(PlayerView v){if(v==null)return;int m=AspectRatioFrameLayout.RESIZE_MODE_FIT;if(resizeMode==1)m=AspectRatioFrameLayout.RESIZE_MODE_ZOOM;else if(resizeMode==2)m=AspectRatioFrameLayout.RESIZE_MODE_FILL;else if(resizeMode==3)m=getResources().getConfiguration().orientation==Configuration.ORIENTATION_LANDSCAPE?AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT:AspectRatioFrameLayout.RESIZE_MODE_FIXED_WIDTH;v.setResizeMode(m);}
  void cycleResizeMode(){resizeMode=(resizeMode+1)%4;applyResizeMode(playerView);savePrefs();toast("Formato: "+resizeModeName());}
  void openFullscreen(){if(current==null){toast("Selecciona un canal primero");return;}final Dialog dlg=new Dialog(this,android.R.style.Theme_Material_NoActionBar_Fullscreen);FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);ViewParent old=playerView.getParent();if(old instanceof ViewGroup)((ViewGroup)old).removeView(playerView);root.addView(playerView,new FrameLayout.LayoutParams(-1,-1));applyResizeMode(playerView);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(10),dp(6),dp(10),dp(6));bar.setBackgroundColor(Color.argb(190,4,12,23));TextView name=tv(current.name,14,Color.WHITE);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(name,new LinearLayout.LayoutParams(0,dp(46),1));Button fit=iconBtn(resizeModeName(),R.drawable.pv_ic_crop);Button close=dangerBtn("Cerrar");bar.addView(fit,new LinearLayout.LayoutParams(dp(118),dp(44)));bar.addView(close,new LinearLayout.LayoutParams(dp(104),dp(44)));FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-1,dp(58),Gravity.BOTTOM);root.addView(bar,bp);fit.setOnClickListener(v->{cycleResizeMode();fit.setText(resizeModeName());});close.setOnClickListener(v->dlg.dismiss());dlg.setOnDismissListener(d->{attachMainPlayer();if(player!=null)player.setVolume(1f);});dlg.setContentView(root);dlg.show();Window w=dlg.getWindow();if(w!=null){w.setStatusBarColor(Color.BLACK);w.setNavigationBarColor(Color.BLACK);w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}}

  void setLiveStatus(String s,int color){if(status!=null){status.setText(s);status.setTextColor(color);}}
  String channelPositionText(){if(current==null)return "";int i=all.indexOf(current);return i>=0?" · "+(i+1)+"/"+all.size():"";}
  boolean networkConnected(){try{ConnectivityManager cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();if(n==null)return false;NetworkCapabilities cp=cm.getNetworkCapabilities(n);return cp!=null&&cp.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}catch(Exception e){return true;}}
  void armStartupWatchdog(final int token){cancelStartupWatchdog();startupWatchdog=()->{if(token!=playToken||current==null||player==null||player.getPlaybackState()==Player.STATE_READY)return;setLiveStatus("Respuesta lenta · reconectando…",ORANGE);if(autoRetryEnabled)autoRetry();};mainHandler.postDelayed(startupWatchdog,12000);}
  void cancelStartupWatchdog(){if(startupWatchdog!=null){mainHandler.removeCallbacks(startupWatchdog);startupWatchdog=null;}}
  String errorLabel(PlaybackException e){String n=e==null?"":e.getErrorCodeName();String u=n.toUpperCase(Locale.ROOT);if(u.contains("NETWORK")||u.contains("TIMEOUT"))return "Problema de red · reintentando";if(u.contains("BAD_HTTP_STATUS")||u.contains("FILE_NOT_FOUND"))return "Enlace no disponible · reintentando";if(u.contains("PARSING")||u.contains("DECOD"))return "Formato de señal no compatible";return "Canal sin respuesta · reintentando";}
  void validateCurrent(){final Channel ch=current;if(ch==null){toast("Selecciona un canal primero");return;}setLiveStatus("Verificando enlace…",CYAN);io.submit(()->{long t=SystemClock.elapsedRealtime();String result;boolean ok=false;HttpURLConnection h=null;try{URL u=new URL(ch.url);URLConnection raw=u.openConnection();raw.setConnectTimeout(6000);raw.setReadTimeout(6000);raw.setRequestProperty("User-Agent","PalmaVision/2.0.3");if(raw instanceof HttpURLConnection){h=(HttpURLConnection)raw;h.setRequestMethod("GET");h.setRequestProperty("Range","bytes=0-1023");h.setInstanceFollowRedirects(true);int code=h.getResponseCode();ok=code>=200&&code<400;result="HTTP "+code+" · "+(SystemClock.elapsedRealtime()-t)+" ms";}else{raw.connect();ok=true;result=u.getProtocol().toUpperCase(Locale.ROOT)+" · "+(SystemClock.elapsedRealtime()-t)+" ms";}}catch(Exception ex){result="Sin respuesta · "+ex.getClass().getSimpleName();}finally{if(h!=null)h.disconnect();}final boolean good=ok;final String msg=result;runOnUiThread(()->{lastHealth=msg;setLiveStatus(good?"Canal responde · "+msg:"Sin respuesta · "+msg,good?GREEN:ORANGE);toast(good?"Enlace del canal disponible":"El enlace no respondió a la verificación");});});}

  void styleDialog(AlertDialog d){d.setOnShowListener(x->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(rounded(PV_SURFACE,18));w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams lp=w.getAttributes();lp.dimAmount=.72f;w.setAttributes(lp);}TextView m=d.findViewById(android.R.id.message);if(m!=null){m.setTextColor(Color.WHITE);m.setTextSize(15);}int tid=getResources().getIdentifier("alertTitle","id","android");TextView at=tid==0?null:d.findViewById(tid);if(at!=null){at.setTextColor(Color.WHITE);at.setTextSize(20);}ListView l=d.getListView();if(l!=null){l.setBackgroundColor(PV_SURFACE);l.setDivider(new ColorDrawable(Color.argb(90,0,198,255)));l.setDividerHeight(1);}Button p=d.getButton(AlertDialog.BUTTON_POSITIVE),n=d.getButton(AlertDialog.BUTTON_NEGATIVE);if(p!=null)p.setTextColor(CYAN);if(n!=null)n.setTextColor(MUTED);});d.show();}
  void pvMessage(String title,String message){AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("Cerrar",null).create();styleDialog(d);}
  void diagnostics(){pvMessage("Diagnóstico PalmaVision","Versión: 2.0.3 Performance & Sources\nCanales: "+all.size()+"\nFavoritos: "+favorites.size()+"\nRecientes: "+recents.size()+"\nRed activa: "+(networkConnected()?"Sí":"No")+"\nCanal actual: "+(current==null?"Ninguno":current.name)+"\nÚltima verificación: "+lastHealth+"\nPermisos: INTERNET + ACCESS_NETWORK_STATE\nBuild: release / no-debuggable\nReproductor: Media3 / ExoPlayer");}
  void confirmExit(){AlertDialog d=new AlertDialog.Builder(this).setTitle("Salir de PalmaVision").setMessage("¿Deseas cerrar la aplicación?").setNegativeButton("Cancelar",null).setPositiveButton("Salir",(x,w)->finishAndRemoveTask()).create();styleDialog(d);}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}

  void loadSavedSource(){SharedPreferences p=getSharedPreferences("tvplus",MODE_PRIVATE);String type=p.getString("source_type",""),uri=p.getString("m3u_uri",""),url=p.getString("m3u_url","");if("xtream".equals(type)){String s=p.getString("xtream_server",""),u=p.getString("xtream_user",""),pw=p.getString("xtream_pass","");if(!s.isEmpty()&&!u.isEmpty()&&!pw.isEmpty()){loadXtream(s,u,pw);return;}}if("local".equals(type)&&!uri.isEmpty()){loadFromUri(Uri.parse(uri),"Archivo M3U local");return;}if("url".equals(type)&&!url.isEmpty()){loadFromUrl(url,"URL M3U");return;}if(!uri.isEmpty()){loadFromUri(Uri.parse(uri),"Archivo M3U local");return;}if(!url.isEmpty()){loadFromUrl(url,"URL M3U");return;}loadDefault();}
  void loadDefault(){setLoading("Cargando lista…","Lista principal");io.submit(()->{List<Channel> parsed;try{parsed=parse(getAssets().open("TV_Espanol_Plus_VERIFICADA.m3u"));}catch(Exception e){parsed=Collections.emptyList();}applyChannels(parsed,"Lista principal");});}
  void loadFromUrl(String url,String label){setLoading("Cargando M3U…",label);io.submit(()->{try{URLConnection c=new URL(url).openConnection();c.setConnectTimeout(5000);c.setReadTimeout(9000);c.setRequestProperty("User-Agent","PalmaVision/2.0.3");List<Channel> p=parse(c.getInputStream());if(p.isEmpty())throw new IOException("Lista vacía");applyChannels(p,label);}catch(Exception e){runOnUiThread(()->toast("No se pudo cargar la lista: "+e.getMessage()));}});}
  void loadFromUri(Uri uri,String label){setLoading("Leyendo archivo M3U…",label);io.submit(()->{try(InputStream in=getContentResolver().openInputStream(uri)){List<Channel> p=parse(in);if(p.isEmpty())throw new IOException("Lista vacía");applyChannels(p,label);}catch(Exception e){runOnUiThread(()->toast("No se pudo leer M3U: "+e.getMessage()));}});}
  void setLoading(String s,String src){runOnUiThread(()->{if(count!=null)count.setText(s);if(sourceText!=null)sourceText.setText(src);});}
  void applyChannels(List<Channel> p,String label){runOnUiThread(()->{all.clear();all.addAll(p);activeSourceLabel=label;rebuildChannelIndex();if(sourceText!=null)sourceText.setText(label);if(adapter!=null)filter();if("livecats".equals(page))showLiveCategories();else if("countries".equals(page))showCountries();});}

  void loadPrefs(){SharedPreferences p=getSharedPreferences("tvplus",MODE_PRIVATE);favorites.addAll(p.getStringSet("favorites",Collections.emptySet()));String r=p.getString("recents","");if(!r.isEmpty())for(String s:r.split("\\|"))if(!s.isEmpty())recents.add(s);autoRetryEnabled=p.getBoolean("auto_retry",true);resizeMode=p.getInt("resize_mode",0);}
  void savePrefs(){getSharedPreferences("tvplus",MODE_PRIVATE).edit().putStringSet("favorites",new HashSet<>(favorites)).putString("recents",joinRecents()).putBoolean("auto_retry",autoRetryEnabled).putInt("resize_mode",resizeMode).apply();}
  String joinRecents(){StringBuilder b=new StringBuilder();for(String id:recents){if(b.length()>0)b.append("|");b.append(id);}return b.toString();}

  @Override public boolean dispatchKeyEvent(KeyEvent e){if(e.getAction()==KeyEvent.ACTION_DOWN){if(e.getKeyCode()==KeyEvent.KEYCODE_MEDIA_NEXT){step(1);return true;}if(e.getKeyCode()==KeyEvent.KEYCODE_MEDIA_PREVIOUS){step(-1);return true;}}return super.dispatchKeyEvent(e);}
  @Override public void onBackPressed(){if("live".equals(page)){showLiveCategories();}else if("countries".equals(page)){showLiveCategories();}else if("livecats".equals(page)){showHome();}else if(!"home".equals(page)){showHome();}else confirmExit();}
  @Override protected void onDestroy(){cancelStartupWatchdog();mainHandler.removeCallbacksAndMessages(null);super.onDestroy();if(player!=null)player.release();io.shutdownNow();}

  static final Pattern GROUP=Pattern.compile("group-title=\\\"([^\\\"]*)\\\""),ID=Pattern.compile("tvg-id=\\\"([^\\\"]*)\\\"");
  static List<Channel> parse(InputStream in)throws IOException{ArrayList<Channel> out=new ArrayList<>();if(in==null)return out;try(BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line,meta=null;while((line=br.readLine())!=null){line=line.trim();if(line.startsWith("#EXTINF:"))meta=line;else if(!line.isEmpty()&&!line.startsWith("#")&&meta!=null){String name=meta.contains(",")?meta.substring(meta.lastIndexOf(',')+1).trim():"Canal";Matcher gm=GROUP.matcher(meta),im=ID.matcher(meta);String group=gm.find()?gm.group(1):"Otros";String id=im.find()&&im.group(1).trim().length()>0?im.group(1):sha1(name+"|"+line);out.add(new Channel(id,name,group,line));meta=null;}}}return out;}
  static String sha1(String s){try{byte[] b=MessageDigest.getInstance("SHA-1").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}catch(Exception e){return Integer.toHexString(s.hashCode());}}
  static final class Channel{final String id,name,group,url,search;Channel(String i,String n,String g,String u){id=i;name=n;group=g;url=u;search=(n+" "+g).toLowerCase(Locale.ROOT);}}
}