plugins { id 'com.android.application' }
android {
  namespace 'com.epalma.tvespanolplus'
  compileSdk 35
  defaultConfig {
    applicationId 'com.epalma.tvespanolplus'
    minSdk 23
    targetSdk 35
    versionCode 181
    versionName '1.8.1'
  }
  buildTypes {
    release {
      debuggable false
      minifyEnabled false
      shrinkResources false
      signingConfig signingConfigs.debug
    }
  }
  compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
  implementation 'androidx.media3:media3-exoplayer:1.5.1'
  implementation 'androidx.media3:media3-exoplayer-hls:1.5.1'
  implementation 'androidx.media3:media3-ui:1.5.1'
  implementation 'androidx.fragment:fragment:1.8.5'
  implementation 'com.google.android.gms:play-services-cast-framework:22.2.0'
}