plugins { id 'com.android.application' }
android {
  namespace 'com.epalma.tvespanolplus'
  compileSdk 35
  defaultConfig {
    applicationId 'com.epalma.tvespanolplus'
    minSdk 24
    targetSdk 35
    versionCode 245
    versionName '2.4.5'
  }
  buildTypes {
    release {
      debuggable false
      minifyEnabled false
      shrinkResources false
      signingConfig signingConfigs.debug
    }
  }
  compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
  testImplementation 'junit:junit:4.13.2'
  implementation 'androidx.media3:media3-exoplayer:1.5.1'
  implementation 'androidx.media3:media3-exoplayer-hls:1.5.1'
  implementation 'androidx.media3:media3-ui:1.5.1'
  implementation 'com.google.android.gms:play-services-cast-framework:22.3.1'
  implementation 'androidx.appcompat:appcompat:1.7.0'
  implementation 'androidx.mediarouter:mediarouter:1.7.0'
}